___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Авторские права принадлежат Pierian Data</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy 

NumPy - это мощная библиотека Python для линейной алгебры. Почти все другие библиотеки в экосистеме <a href='https://pydata.org/'>PyData</a>  (pandas, scipy, scikit-learn и т.д.) используют внутри себя NumPy. А ещё, чуть позже, мы с помощью этой библиотеки сгенерим данные для наших примеров!

NumPy работает очень быстро, поскольку содержит ссылки на библиотеки, написанные на C. Более подробно почитать о том, почему лучше использовать массивы вместо списков, Вы можете в [этой статье на StackOverflow (англ.)](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Мы изучим только основы NumPy. Начнём с установки!

## *Замечание*: Инструкции по установке Numpy

### NumPy уже есть в Вашей среде environment! Мы ОЧЕНЬ рекомендуем Вам использовать те настройки, которые показаны в лекции по установке и настройке. Если Вы используете среду, которая предлагается в курсе, то у Вас всё должно быть хорошо!

_____
##### Для тех, кто не использует предлагаемую среду:

**Мы рекомендуем установить Python, используя дистрибутив Anaconda. В этом случае можно обеспечить наличие зависимых библиотек (таких как библиотеки линейной алгебры), используя команду conda install. Если у Вас есть Anaconda, то установите NumPy следующим образом - откройте командную строку или терминал, и введите следующую команду:**
    
    conda install numpy
    
    
**Если Вы по каким-то причинам не можете установить Anaconda, то можете посмотреть [официальную документацию Numpy, в которой приведены инструкции для различных вариантов установки.](https://www.scipy.org/install.html)**

_____

## Импортируем NumPy

После установки NumPy, Вы можете импортировать его как библиотеку:

In [4]:
import numpy as np

В NumPy есть много встроенных функций и возможностей. Мы не будем рассматривать их все, а рассмотрим только наиболее важные аспекты NumPy: векторы (vectors), массивы (arrays), матрицы (matrices) и генерация чисел. Начнём с массивов.

# Массивы NumPy

Мы будем часто использовать массивы NumPy на протяжении всего курса. Массивы NumPy бывают двух типов: векторы (vectors) и матрицы (matrices). Векторы - это строго одноразмерные массивы (1D), а матрицы - двумерные массивы (2D). Следует однако заметить, что матрица может состоять только из одной строки или только из одного столбца.

## Зачем использовать массивы Numpy? Почему нельзя просто использовать список?

Есть много причин, по которым массивы Numpy могут быть лучше "стандартного" списка List в Python.  
Наши основные причины следующие:
* Эффективное управление памятью
* Легко расширяется до N-размерных объектов
* Скорость вычислений для массивов numpy
* Возможность применять операции и функции сразу для всех элементов массива (broadcasting)
* Все библиотеки data science и машинного обучения, которые мы будем использовать, построены на основе Numpy


Начнём с рассмотрения различных способов создания массивов NumPy.

## Создание массивов NumPy на основе Объектов

### На основе списка Python

Мы можем сконвертировать список или "список списков" в массив:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Встроенные методы для создания списков

Существует много встроенных методов для генерации массивов.

### arange

Возвращает равноудалённые друг от друга значения в заданном интервале. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros и ones - нули и единицы

Создание массивов из нулей или единиц. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Возвращает равноудалённые друг от друга числа в заданном интервале. [[документация (англ.)](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]  
Этот метод очень похож на arange, но если в arange мы указывали шаг между числами, то в linspace мы указываем количество чисел. Это особенно полезно для чисел float.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Обратите внимание, что `.linspace()` *включает* верхнюю границу диапазона. Поэтому если, например,мы хотим  разделить интервал от 0 до 5 на 20 отрезков, то нужно указать количество чисел 21:</font>

In [14]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Создаёт единичную матрицу - единицы на главной диагонали, остальные нули [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Случайные числа (Random Numbers)
В Numpy есть много разных способов создавать массивы со случайными числами:

### rand
Создаёт массив указанной размерности, и заполняет его случайными числами с равномерным распределением вероятности на отрезке ``[0, 1)``. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [16]:
np.random.rand(2)

array([0.37065108, 0.89813878])

In [17]:
np.random.rand(5,5)

array([[0.03932992, 0.80719137, 0.50145497, 0.68816102, 0.1216304 ],
       [0.44966851, 0.92572848, 0.70802042, 0.10461719, 0.53768331],
       [0.12201904, 0.5940684 , 0.89979774, 0.3424078 , 0.77421593],
       [0.53191409, 0.0112285 , 0.3989947 , 0.8946967 , 0.2497392 ],
       [0.5814085 , 0.37563686, 0.15266028, 0.42948309, 0.26434141]])

### randn

Возвращает сэмпл (или сэмплы) из стандартного нормального распределения [σ = 1] в диапазоне от -1 до +1. В отличие от **rand** , в котором распределение равномерное, здесь более вероятны значения в середине диапазона (около нуля). [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [18]:
np.random.randn(2)

array([-0.36633217, -1.40298731])

In [19]:
np.random.randn(5,5)

array([[-0.45241033,  1.07491082,  1.95698188,  0.40660223, -1.50445807],
       [ 0.31434506, -2.16912609, -0.51237235,  0.78663583, -0.61824678],
       [-0.17569928, -2.39139828,  0.30905559,  0.1616695 ,  0.33783857],
       [-0.2206597 , -0.05768918,  0.74882883, -1.01241629, -1.81729966],
       [-0.74891671,  0.88934796,  1.32275912, -0.71605188,  0.0450718 ]])

### randint
Возвращает случайные целые числа в диапазоне от `low` (включительно) до `high` (не включая это значение).  [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [20]:
np.random.randint(1,100)

61

In [21]:
np.random.randint(1,100,10)

array([39, 50, 72, 18, 27, 59, 15, 97, 11, 14])

### seed
Эту функцию можно использовать для задания начальной точки генерации случайных чисел, чтобы можно было воспроизвести одни и те же "случайные" числа. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [22]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Атрибуты и методы массивов

Давайте обсудим некоторые полезные атрибуты и методы для массивов:

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Возвращает массив с теми же данными, но с новой размерностью массива. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Это полезные методы для поиска максимального и минимального значения, а также их местоположения с помощью argmax и argmin

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [29]:
ranarr.max()

39

In [30]:
ranarr.argmax()

7

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmin()

9

## Shape

Shape - это атрибут массивов (не метод):  [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [33]:
# Вектор
arr.shape

(25,)

In [34]:
# Обратите внимание на два набора скобок
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Вы можете также посмотреть тип данных объектов внутри массива: [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [38]:
arr.dtype

dtype('int32')

In [39]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Отличная работа!